<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Ansonika">
    <title>UDEMA - Teacher dashboard</title>

    <!-- Favicons-->
    <link rel="shortcut icon" href="../../../admin_section/img/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" type="image/x-icon" href="../../../admin_section/img/apple-touch-icon-57x57-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="../../../admin_section/img/apple-touch-icon-72x72-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="../../../admin_section/img/apple-touch-icon-114x114-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="../../../admin_section/img/apple-touch-icon-144x144-precomposed.png">

    <!-- GOOGLE WEB FONT -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800" rel="stylesheet">

    <!-- Bootstrap core CSS-->
    <link href="../../../admin_section/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Main styles -->
    <link href="../../../admin_section/css/admin.css" rel="stylesheet">
    <!-- Icon fonts-->
    <link href="../../../admin_section/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- Plugin styles -->
    <link href="../../../admin_section/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <link href="../../../admin_section/vendor/dropzone.css" rel="stylesheet">
    <!-- Your custom styles -->
    <link href="../../../admin_section/css/custom.css" rel="stylesheet">

    <link href="../../../admin_section/css/date_picker.css" rel="stylesheet">

    <!-- Plugin styles -->
    <link href="../../../admin_section/vendor/animate.min.css" rel="stylesheet">
    <link href="../../../admin_section/vendor/magnific-popup.css" rel="stylesheet">

</head>