<!-- Bootstrap core JavaScript-->
<script src="../../../admin_section/vendor/jquery/jquery.min.js"></script>
<script src="../../../admin_section/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="../../../admin_section/vendor/jquery-easing/jquery.easing.min.js"></script>
<!-- Page level plugin JavaScript-->
<script src="../../../admin_section/vendor/chart.js/Chart.min.js"></script>
<script src="../../../admin_section/vendor/datatables/jquery.dataTables.js"></script>
<script src="../../../admin_section/vendor/datatables/dataTables.bootstrap4.js"></script>
<script src="../../../admin_section/vendor/jquery.selectbox-0.2.js"></script>
<script src="../../../admin_section/vendor/retina-replace.min.js"></script>
<script src="../../../admin_section/vendor/jquery.magnific-popup.min.js"></script>
<!-- Custom scripts for all pages-->
<script src="../../../admin_section/js/admin.js"></script>
<!-- Custom scripts for this page-->
<script src="../../../admin_section/vendor/dropzone.min.js"></script>

<script src="../../../admin_section/vendor/bootstrap-datepicker.js"></script>



<script>$('input.date-pick').datepicker();</script>