<!DOCTYPE html>
<html lang="en">

<?php
require_once 'parts/head_profile.phtml';
?>

<body class="fixed-nav sticky-footer" id="page-top">
  <!-- Navigation-->
  <?php
  require_once 'parts/nav_profile.phtml';
  ?>
  <!-- /Navigation-->
  <div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Bookmarks</li>
      </ol>
		<div class="box_general">
			<div class="header_box">
				<h2 class="d-inline-block">Bookmarks</h2>
				<div class="filter">
					<select name="orderby" class="selectbox">
						<option value="Any time">Any time</option>
						<option value="Latest">Latest</option>
						<option value="Oldest">Oldest</option>
					</select>
				</div>
			</div>
			<div class="list_general">
				<ul>
                    <?php foreach ($bookmarks as $bookmark):?>
					<li>
						<figure><img src="../../admin_section/img/course_1.jpg" alt=""></figure>
						<small><?=$bookmark['categoriesName']?></small>
						<h4><?=$bookmark['coursesName']?></h4>
						<p><?=$bookmark['coursesDescription']?></p>
						<p><a href="/courses-detail/<?=$bookmark['courseId']?>" class="btn_1 gray"><i class="fa fa-fw fa-eye"></i> View course</a></p>
						<ul class="buttons">
							<li><a href="/wishList?course_id=<?=$bookmark['courseId']?>" class="btn_1 gray delete wishlist_close"><i class="fa fa-fw fa-times-circle-o"></i> Cancel</a></li>
						</ul>
					</li>
                    <?php endforeach; ?>
				</ul>
			</div>
		</div>
		<!-- /box_general-->
		<nav aria-label="...">
			<ul class="pagination pagination-sm add_bottom_30">
				<li class="page-item disabled">
					<a class="page-link" href="#" tabindex="-1">Previous</a>
				</li>
				<li class="page-item"><a class="page-link" href="#">1</a></li>
				<li class="page-item"><a class="page-link" href="#">2</a></li>
				<li class="page-item"><a class="page-link" href="#">3</a></li>
				<li class="page-item">
					<a class="page-link" href="#">Next</a>
				</li>
			</ul>
		</nav>
		<!-- /pagination-->
	  </div>
	  <!-- /container-fluid-->
   	</div>
    <!-- /container-wrapper-->
    <footer class="sticky-footer">
      <div class="container">
        <div class="text-center">
          <small>Copyright © UDEMA 2018</small>
        </div>
      </div>
    </footer>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
  <?php
  require_once 'parts/modal_logout.phtml';
  ?>
  <?php
  require_once 'parts/scripts_profile.phtml';
  ?>

	
</body>
</html>
