<!DOCTYPE html>
<html lang="en">

<?php
require_once 'parts/head_profile.phtml';
?>

<body class="fixed-nav sticky-footer" id="page-top">
  <?php
    require_once 'parts/nav_profile.phtml';
  ?>
  <div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Profile</li>
      </ol>
		<form class="box_general padding_bottom" method="post" action="/update_profile">
			<div class="header_box version_2">
				<h2><i class="fa fa-file"></i>Basic info</h2>
			</div>
			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<label>Name</label>
						<input type="text" name="name" class="form-control" placeholder="Your name" value="<?=$user->name?>">
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<label>Last name</label>
						<input type="text" name="last_name" class="form-control" placeholder="Your last name" value="<?=$user->last_name?>">
					</div>
				</div>
			</div>
			<!-- /row-->
			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<label>Telephone</label>
						<input type="text" name="phone" class="form-control" placeholder="Your telephone number" value="<?=$user->phone?>">
					</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
						<label>Email</label>
						<input type="email" name="email" class="form-control" placeholder="Your email" value="<?=$user->email?>">
					</div>
				</div>
			</div>
			<!-- /row-->
<!--			<div class="row">-->
<!--				<div class="col-md-12">-->
<!--					<div class="form-group">-->
<!--						<label>Profile picture</label>-->
<!--                        <input type="file" class="dropzone" name="img_profile">-->
<!--						<form action="/file-upload" class="dropzone"></form>-->
<!--					</div>-->
<!--				</div>-->
<!--			</div>-->
            <input type="submit" class="btn_1 medium" value="Save">
			<!-- /row-->
		</form>
		<!-- /box_general-->

<!--		<form class="box_general padding_bottom" action="/dhfsdhfisfidfs" method="post">-->
<!--			<div class="header_box version_2">-->
<!--				<h2><i class="fa fa-file-text"></i>Curriculum</h2>-->
<!--			</div>-->
<!--			<div class="row">-->
<!--				<div class="col-md-12">-->
<!--					<div class="form-group">-->
<!--						<label>Professional statement</label>-->
<!--						<textarea rows="5" class="form-control" style="height:100px;" placeholder="Description"></textarea>-->
<!--					</div>-->
<!--				</div>-->
<!--			</div>-->
			<!-- /row-->
<!--			<div class="row">-->
<!--				<div class="col-md-12">-->
<!--					<div class="form-group">-->
<!--						<label>Specialization <a href="#0" data-toggle="tooltip" data-placement="top" title="Separated by commas"><i class="fa fa-fw fa-question-circle"></i></a></label>-->
<!--						<input type="text" class="form-control" placeholder="Ex: Biologist, Pediatrician...">-->
<!--					</div>-->
<!--				</div>-->
<!--			</div>-->
<!--            <input type="submit" class="btn_1 medium" value="Save">-->
			<!-- /row-->
<!--		</form>-->
		<!-- /box_general-->

		<p>

	  </div>
	  <!-- /.container-fluid-->
   	</div>
    <!-- /.container-wrapper-->
    <footer class="sticky-footer">
      <div class="container">
        <div class="text-center">
          <small>Copyright © UDEMA 2018</small>
        </div>
      </div>
    </footer>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
  <?php
  require_once 'parts/modal_logout.phtml';
  ?>

  <?php
  require_once 'parts/scripts_profile.phtml';
  ?>
	
</body>
</html>
